export const ESTATS_TASCA = {
  PENDENT: 'PENDENT',
  EN_CURS: 'EN_CURS',
  FINALITZADA: 'FINALITZADA'
};

export const TIPUS_TASCA = {
  ADMINISTRATIU: 'ADMINISTRATIU',
  PEDAGOGIC: 'PEDAGOGIC',
  TECNIC: 'TECNIC'
};
