import {
  ESTATS_ASSIGNACIO,
  ESTATS_DISPOSITIU,
  ESTATS_INCIDENCIA,
  TIPUS_DISPOSITIU
} from '../../../shared/constants.js';

export {
  ESTATS_ASSIGNACIO,
  ESTATS_DISPOSITIU,
  ESTATS_INCIDENCIA,
  TIPUS_DISPOSITIU
};

export const TIPUS_DISPOSITIU_VALUES = Object.values(TIPUS_DISPOSITIU);
export const ESTATS_DISPOSITIU_VALUES = Object.values(ESTATS_DISPOSITIU);
export const ESTATS_ASSIGNACIO_VALUES = Object.values(ESTATS_ASSIGNACIO);
export const ESTATS_INCIDENCIA_VALUES = Object.values(ESTATS_INCIDENCIA);
